---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root

  # sample tasks to ensure things *just work*
  tasks:

    - name: view current distro
      shell: cat /etc/*-release
      register: distro
    - debug: var=distro

    # perform an action that requires root access
    - name: create user foo
      user: name=foo
