---
- hosts: all
  gather_facts: no
  become: true
  tasks:

  - name: Add a new user named devops
    user:
       name: "{{ username }}"
       shell: '/bin/bash'
       password: "{{ userpassword }}"
